<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Aspire.SLA.Aws</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Aspire.SLA\Aspire.SLA.csproj" />
      <PackageReference Include="Aspire.Hosting" />
    </ItemGroup>

</Project>
